### ISSUE TITLE
Implement Face Detection filter

### ISSUE THREAD

**Issue by ugnelis** [ugnelis/ros-cameras-controller#14]
It would be nice to have face detection filter. Face detection could be made with Haar Cascades (https://docs.opencv.org/3.4.3/d7/d8b/tutorial_py_face_detection.html). 

Filter must be ROS nodelet and has to be located in https://github.com/ugnelis/ros_cameras_controller/tree/master/image_processing_filters. In this subproject there is a Threshold example.

**Comment by rummanwaqar** [comment]
@ugnelis I will work on it. Do you want a mask or a ROI?

**Comment by ugnelis** [comment]
@rummanwaqar any approach is welcome!
